# Generated by Django 5.1.3 on 2024-11-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecpies', '0006_remove_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Cooking time in minutes'),
        ),
    ]
